Implement functionality to check for candidate status and process accordingly.
FreddieMwau/Onboarding_Email_Handler pull request #5
Opened 2024-02-20 08:17 UTC by itsMoriss

2024-02-20 11:47 UTC, FreddieMwau requested changes
Great work, you just missed handling the :
* system exceptions on the RejectedStatus, HiredStatus & Check Status xaml

2024-02-20 11:47 UTC, FreddieMwau commented on Manipulate Letters/CheckStatus.xaml
Great implementation, I think you missed handling the system exception because it's empty with no activities on this xaml

2024-02-20 11:47 UTC, FreddieMwau commented on Manipulate Letters/HiredStatus.xaml
Great implementation, I think you missed handling the system exception because it's empty with no activities on this xaml

2024-02-20 11:47 UTC, FreddieMwau commented on Manipulate Letters/RejectedStatus.xaml
Great implementation, I think you missed handling the system exception because it's empty with no activities on this xaml

2024-02-21 11:26 UTC, itsMoriss commented on Manipulate Letters/RejectedStatus.xaml
Addressed changes requested.

2024-02-21 11:29 UTC, itsMoriss commented
Added activities in the Catch block to capture screenshots of errors and attach them to email notifications sent to specified email addresses.

2024-02-21 13:03 UTC, FreddieMwau requested changes
Have the email body & subject in the Config file Constants tab and don't assign it as such
![image](https://github.com/FreddieMwau/Onboarding_Email_Handler/assets/37485156/ce0ba2bb-6d80-4197-93fd-9dc6714b4be6)
on CheckStatus, HiredStatus, RejectedStatus xamls

2024-02-23 12:01 UTC, FreddieMwau commented
You haven't handled the email body and subject in the config excel folder

2024-02-23 12:02 UTC, FreddieMwau requested changes
You haven't handled the email body and subject in the config excel folder

2024-02-23 12:13 UTC, FreddieMwau approved these changes

2024-02-23 12:15 UTC, FreddieMwau requested changes

2024-02-23 12:15 UTC, FreddieMwau commented on Manipulate Letters/CheckStatus.xaml
![image](https://github.com/FreddieMwau/Onboarding_Email_Handler/assets/37485156/986dc1bf-3637-40e2-975c-17041822f8e2)

Make similar exception changes on this xaml, you missed it (CheckStatus.xaml)

2024-02-23 12:18 UTC, FreddieMwau approved these changes

2024-02-23 12:18 UTC, merged